### ISSUE TITLE
Landmark localization on 2d face images using 3d models

### ISSUE THREAD

**Issue by ddfabbro** [1adrianb/face-alignment#118]
I started reading your paper and watched [your demo video over youtube](https://youtu.be/8FdSHl4oNIM).

However, at [1:04](https://youtu.be/8FdSHl4oNIM?t=64), the alignment network is able to detect the landmarks of the presenters, but not the picture in the background.

I'm curious, why isn't the model detecting landmarks on 2d face images?

Anyways, the results are very impressive, thanks for sharing.

**Comment by 1adrianb** [comment]
Hi @ddfabbro,
Thanks a lot!
Its simple because by mistake I have ignored the face when plotting. There is no reason for it now to work on that particular face. Please note however, that the demo was also produced a bit differently: a detector was run only on the first frame and the subsequent ones were simply initialised from the previous alignment.
