### ISSUE TITLE
cuda runtime error (11) 

### ISSUE THREAD

**Issue by cristinasegalin** [1adrianb/face-alignment#123]
I tried to run the code only changing the face detector with cvlib, and then I get this error.
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:

if I change the dace detector to the one I implemented using as well cuda I get the error even before the landmark detection. 
I  am not sure where it comes from..as the variables and input are all correct, could it be something realted to out of memory? I have 4 RTX 2080

**Comment by 1adrianb** [comment]
@cristinasegalin can you please make sure that you have at least cuda 9.2 and the latest pytorch version (1.0)? Some people were reporting issues with lower versions of cuda.
Regarding a potential out of memory, it is possible but unlikely. To rull this out make sure that your input image is relatively small since the image detectors may go out of memory at large resolutions.

**Comment by cristinasegalin** [comment]
I have cuda 10. And using Yolov3 as face detector on a separate gpu.
I was trying to use the same image used in the example shared with the repo


Cristina

**Comment by cristinasegalin** [comment]
solved compiling pytorch from source

**Comment by 1adrianb** [comment]
Great to know that you found and fixed the issue!

**Comment by c1a1o1** [comment]
Compiling pytorch from source ? @cristinasegalin 
How to do this???

**Comment by daniaokuye** [comment]
if using np.copy before cuda(). the error may disappear!
pre = pre.transpose((2, 0, 1))[np.newaxis,].copy()
x = torch.from_numpy(pre).cuda()
