### ISSUE TITLE
How crop face according outline of face?

### ISSUE THREAD

**Issue by jinfagang** [1adrianb/face-alignment#125]
Hi, thanks for your wonderful repo. May I ask a question about my attempt?

I want crop a face out of 2d image. Based on the ouline of face (simply I already get the face rect, but it has background, I wanna crop the face and remove the background or vise-verse.

Can it be done this this repo? Thanks in advance

**Comment by 1adrianb** [comment]
Hi @jinfagang sorry for delay. Depends on what you need exactly. The method provides 68 points points located on the face and the edge of the face (see the images from the readme). Note: you need to run the method in 2D mode in order to obtain them in the configuration you need. However please note that there are no points located on the forehead.
