### ISSUE TITLE
how can I achive the efficient and accurate result in your showed video clip

### ISSUE THREAD

**Issue by zeagle01** [1adrianb/face-alignment#17]
hi @1adrianb 
after days of installation, I finally make it to run the program on windows
so I tried it at some image sequence to reproduce the result as in the video clip(Obama and Iron man) you showed
I found it slow(around 0.3 fps for 3D and 0.5 fps for 2D) and not so accurate as in your video clip
so what did I miss?

**Comment by 1adrianb** [comment]
Hi @zeagle01,
Since the method was designed for images and not for videos you may need to apply some post-processing or some tricks at runtime. For example, in the above video, the next location of the face was computed based on the previous fitting (this will result in a more stable bounding box). Additionally, one can run it twice on the same frame initializing the second detection based on the previous one. While there is no post-processing in the above video, ideally one should filter the small noise present in the video examples that I uploaded. 
Also, the model used or very slightly different (the Lua code in torch7 was used for it).

Regarding the speed. The speed reported on the paper was computed on a 1080Ti/Titan X and didn't include the face detection time. Dlib is probably taking most of the time here and it causes the slow down you see. 

I hope this answers your concerns. If not, please let me know.

**Comment by ncuxiaogang** [comment]
@1adrianb You say "For example, in the above video, the next location of the face was computed based on the previous fitting (this will result in a more stable bounding box)." What filtering method should I used to get stable bounding box? Thanks!

**Comment by ncuxiaogang** [comment]
@1adrianb I say I can get the bounding box of the face in each frame, but the frame is not stable. What method should I used to get the stable method?

**Comment by 1adrianb** [comment]
@ncuxiaogang running the code twice should help you achieve better stablity (by initialising from the previous prediction). You can also have a look at smooting techniques (ex: https://www.kaggle.com/selfishgene/animating-and-smoothing-3d-facial-keypoints/ where they actually use data produced by this code)

**Comment by ncuxiaogang** [comment]
@1adrianb Got it, thanks!
