### ISSUE TITLE
Any tips to do real-time face alignment?

### ISSUE THREAD

**Issue by hurricanemad** [1adrianb/face-alignment#19]
Hello Adrian,
Congratulations on achieving so excellent results! I test the 2D FAN and show the feature points in gpu mode. It cost about one minute to do face alignment. I find process time is independent of image size which times on python script. Is there any tips for me  to do real-time face alignment?(10fps is hope for me)

**Comment by 1adrianb** [comment]
Hi @hurricanemad ,
Thank you! The uploaded model can run at 20fps+ on a high-end GPU (detector time excluded). First, please check if this slowdown is not caused by dlib. 
I am planning to upload some smaller models, up to 8x faster with minimal perforamance loss but this may take 2 or 3 weeks. 
As an alternative please have a look on this: https://github.com/1adrianb/binary-face-alignment

**Comment by hurricanemad** [comment]
Thanks very much! I really appreciate it! I read the thesis you  published. How amazingly alignment do in 30 fps. I try to do face detection using MTCNN and face alignment with your net. Look forward to your nice result!

**Comment by uday60** [comment]
@1adrianb 
Is this code available in python or c++ ?
