### ISSUE TITLE
Aaron's vrn vs Adrian's face-alignment

### ISSUE THREAD

**Issue by monabiyan** [1adrianb/face-alignment#21]
Hi Adrian
I am particularly interested in the accurate 3d landmark detection. My question is that in terms of accuracy, which one gives better accuracy : 
your  **face-alignment code**  or **Aaron's vrn**  or they are using the **same model** for landmark detection?
thank you so much

**Comment by 1adrianb** [comment]
Hi @monabiyan ,
We used the same dataset for training, namely 300W-LP. A variation of the face alignment network(FAN) used here was used to guide VRN (see the VRN-guied version in our 3D reconstruction paper).

Since this work has the face alignment problem as the main objective, and since a variation of FAN was used to guide VRN, the 68 points predicted here should be more accurate in general.
Howver if you need more than 68 points you can probably get the from the mesh predicted by VRN.

**Comment by monabiyan** [comment]
Adrian
Perfect answer. 

Thank you
