### ISSUE TITLE
Index error occurred.

### ISSUE THREAD

**Issue by kisuya** [1adrianb/face-alignment#22]
https://github.com/1adrianb/face-alignment/blob/b981dbb7e1f11d002338d96793903c458b7d4fa1/face_alignment/utils.py#L123

Hi Adrian.

Thank you for sharing your project.
I test your python project and found index error at utils.py(123 line)
In my test environment, sometimes, 63 is assigned to the pY.
So int(pY) + 1 make index error.

Could you tell me how to solve this ?

**Comment by 1adrianb** [comment]
Hi @kisuya ,
Thanks a lot for noticing this. I have fixed the condition, however the fact that this happens in practice suggests that the face was cropped a bit too tight since normally the location of points should be further than that from edges. You should have a look on improving this since a very large deviation from the expected scale may leed to slighly worse results.

**Comment by kisuya** [comment]
Hi @1adrianb 

Thanks for your effort. 
I am a beginner in this field. 
So I am currently studying and want to learn more about your project.
I did not understand your feedback clearly, but I will try harder.
