### ISSUE TITLE
Conversion from 3d to 2d?

### ISSUE THREAD

**Issue by Deccan12** [1adrianb/face-alignment#233]
Can we convert detected 3d facial landmarks for still image to 2D directly or would these landmarks be different for 2D and 3D?

**Comment by 1adrianb** [comment]
The are 3 configuration modes the codes run: 2D, 2.5D and 3D. The 2.5D ones are simply the projection of the 3D ones, so there (x.y) coordinated for the 2.5D and 3D ones is the same.

The 2D ones, due to historical reasons mainly, are annotated at the boundary of the face and they lose correspondence with the actual 2.5D ones for non-frontal faces. To better illustrate the differences between this 2 configurations please see:  Fig. 4 vs Fig. 6 here: http://openaccess.thecvf.com/content_ICCV_2017/papers/Bulat_How_Far_Are_ICCV_2017_paper.pdf

**Comment by Deccan12** [comment]
Thank you, that clears it up.

**Comment by Deccan12** [comment]
> The are 3 configuration modes the codes run: 2D, 2.5D and 3D. The 2.5D ones are simply the projection of the 3D ones, so there (x.y) coordinated for the 2.5D and 3D ones is the same.
> 
> The 2D ones, due to historical reasons mainly, are annotated at the boundary of the face and they lose correspondence with the actual 2.5D ones for non-frontal faces. To better illustrate the differences between this 2 configurations please see: Fig. 4 vs Fig. 6 here: http://openaccess.thecvf.com/content_ICCV_2017/papers/Bulat_How_Far_Are_ICCV_2017_paper.pdf

I ran the code for 100's of images with folloing 2 detectors:



fa2D = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device='cpu', flip_input=True)

fa3D = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, device='cpu', flip_input=True)

But for both of these configuration, i got exact same output, of dimensions (68,3), is it normal or am I missing anything?
