### ISSUE TITLE
Accuracy of  positive faces much worse than side faces?

### ISSUE THREAD

**Issue by QuantumLiu** [1adrianb/face-alignment#43]
I've downloaded new models and codes, and tested on several video frames.
Accuracy of side faces' alignment is excellent.
Curiously, I got even worse results on positive faces.
What might be the reason?
positive faces:
![peek 2018-01-13 21-55](https://user-images.githubusercontent.com/21980268/34912296-b64cb902-f918-11e7-92df-607b4a52fdc5.gif)
side faces
![figure_1](https://user-images.githubusercontent.com/21980268/34912297-ba97ef22-f918-11e7-809b-6d764613eb10.png)

**Comment by 1adrianb** [comment]
Hi, can you attach an input example please so I can have a look?

**Comment by QuantumLiu** [comment]
@1adrianb Thank you for the reply. I might sending example datas to you by Email.

> The dlib face detector is returning a suboptimal bounding box. (most likely) By subtoptimal I mean from a network perspective (ex: at train time this kind of bounding boxes were not simulated)
But dlib's shap_predictor_68 got quite good result.

> Ex: the rounder faces are not really present in the dataset, except for few images with some babies.
This is funny :-)

**Comment by 1adrianb** [comment]
@QuantumLiu sure, I will have a look.
True, however dlib was trained using the behaviour/statistics of its own face detector so its normal to achieve its peak performance by using the dlib detector itself. It is important to note that dlib doesnt predict the 3D coordinates as far as I know, nor does it work  for larger poses or faces found challenging poses/illumination conditions. Anyway, please, feel free to use whatever works best for your scenario.

This models were trained by simple using a jittered (with 20%) ground truth bounding box. Dlib was provided for simplicity and was by no mean included with the purpuse of achieving state-of-the-art results. For achieving such results two simple things can be attempted: a) using a better (ex: faster-rccn based) face detector,  b) retrain the models using the output of dlib bounding boxes (this is challenging since dlib often doesnt detect faces found in large poses) or c)adjust the scale of face (by default its set to 195px in the code)

That been said at the moment I don't have the time to include a better face detector/retrain the models, but I may have a look at a later time.

**Comment by QuantumLiu** [comment]
@1adrianb Very thank you for your work!

**Comment by QuantumLiu** [comment]
Hi， have you received my e-mail? It seems got some problems because I have received 2 'mail delivery failed' message.

**Comment by mrgloom** [comment]
>This models were trained by simple using a jittered (with 20%) ground truth bounding box.

How these ground truth bounding boxes were obtained? At evaluation metrics computed also using these ground truth bounding boxes?
