### ISSUE TITLE
Visualizing FAN and FAN3D

### ISSUE THREAD

**Issue by azmathmoosa** [1adrianb/face-alignment#51]
Hi adrian, I would like to visualize this graph so that I can port this to dlib.  I have tried some pytorch visualization scripts [here](https://discuss.pytorch.org/t/print-autograd-graph/692/6) but I have failed to get them working.

Can you help me in this? Thanks a lot for your effort!

**Comment by 1adrianb** [comment]
Hi @azmathmoosa I am unsure how helpfull it will to be honest due to the high number of layers. You can probably visuale the lua torch packages from here https://github.com/1adrianb/2D-and-3D-face-alignment suing ``nngraph`` or ``optim`` packages. As an alternative, for pytorch you can try: https://github.com/lanpa/tensorboard-pytorch
