### ISSUE TITLE
Speed problem!

### ISSUE THREAD

**Issue by AminHP** [1adrianb/face-alignment#58]
Hi. I've read your comments about the speed of dlib. I've compared the speed of your library and dlib for 2D-landmarks of same images.
The dlib extracts landmarks in 0.1-0.2 secs on CPU.
Your library does it in 4-5 secs on CPU.
It seems dlib is too faster for 2D landmark extraction.
Why is there such a difference?

**Comment by 1adrianb** [comment]
Hi @AminHP ,

On a CPU, this is to be expected. 
As far as I know dlib uses this for for face alignment: http://blog.dlib.net/2014/08/real-time-face-pose-estimation.html which is a implementation of the "One Millisecond Face Alignment with an Ensemble of Regression Trees by Vahid Kazemi and Josephine Sullivan" paper. As the name of the paper suggests the algorithm used is intended to be very fast.

As described in our paper we are using a very deep neural network and while our method will work for faces found in a large variety of poses and will be more accurate in general, especially for difficult poses, the method is noticeable slower. Using a high end  cuda-enabled GPU (ex.  1080Ti ) one can expect up to 30fps (excluding the face detection time). For faster speed one can use a smaller network. 

Since we are discussion about speed you can also have a look on another work that focuses on speed: https://github.com/1adrianb/binary-face-alignment

**Comment by AminHP** [comment]
Oh got it. Thanks you for your quick reply :)
